[package]
name = "mine-rs"
version = "0.1.0"
authors = ["Koen Westendorp <koensswestendorp@icloud.com>"]
edition = "2021"

#[profile.release]
#debug = true

[dependencies]
rand = "0.8"
console = "0.15"
structopt = "0.3"
